<?xml version="1.0" encoding="utf-8"?><Database Name="Teach" Class="DataWRYJCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Teach;User ID=sa" SettingsObjectName="WRYJC.DAL.Properties.Settings" SettingsPropertyName="TeachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataCollectDviceOffline" Member="DataCollectDviceOffline">
    <Type Name="DataCollectDviceOffline">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PollutionPointId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="OfflineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OnlineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HandlerOrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Enterprise" Member="Enterprise">
    <Type Name="Enterprise">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AttachedTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(10,7)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(10,7)" CanBeNull="true" />
      <Column Name="LegalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LegalName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ConcernDegree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdministrationZone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MonitorType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IndustryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Scale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Watershed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalArea" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="IsMonitor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Is30KPower" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnterpriseEnvironmentDept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnvironmentPrincipal" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="EnvironmentPersonCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MailingAddress" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OfficePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bank" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ConnectPerson" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OnlineStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperationStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GasDayData" Member="GasDayData">
    <Type Name="GasDayData">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WasteObjectID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StrengthMax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StrengthAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="StrengthMin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FixStrength" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FlowMax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FlowAvg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FlowMin" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FixFlow" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsException" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CorrectUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CorrectUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CorrectCause" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CorrectTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PollutionPoint" Member="PollutionPoint">
    <Type Name="PollutionPoint">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterpriseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RegionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Watershed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmissionDestination" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmissionRules" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SignInstallForm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FunctionType" Type="System.Decimal" DbType="Decimal(10,7)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(10,7)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysMenu" Member="SysMenu">
    <Type Name="SysMenu">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuIcon" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuUrl" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TheOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SysMenu_SysMenu" Member="SysMenu2" ThisKey="Id" OtherKey="MasterID" Type="SysMenu" />
      <Association Name="SysMenu_SysPower" Member="SysPower" ThisKey="Id" OtherKey="SysMenuID" Type="SysPower" />
      <Association Name="SysMenu_SysMenu" Member="SysMenu1" ThisKey="MasterID" OtherKey="Id" Type="SysMenu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysPower" Member="SysPower">
    <Type Name="SysPower">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SysMenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PowerIcon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PowerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PowerUrl" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SysPower_SysRoleAndSysPower" Member="SysRoleAndSysPower" ThisKey="Id" OtherKey="SysPowerId" Type="SysRoleAndSysPower" />
      <Association Name="SysMenu_SysPower" Member="SysMenu" ThisKey="SysMenuID" OtherKey="Id" Type="SysMenu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysRole" Member="SysRole">
    <Type Name="SysRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DelTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InsertTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SysRole_SysRoleAndSysPower" Member="SysRoleAndSysPower" ThisKey="Id" OtherKey="SysRoleId" Type="SysRoleAndSysPower" />
      <Association Name="SysRole_SysUserAndSysRole" Member="SysUserAndSysRole" ThisKey="Id" OtherKey="SysRoleId" Type="SysUserAndSysRole" />
    </Type>
  </Table>
  <Table Name="dbo.SysRoleAndSysPower" Member="SysRoleAndSysPower">
    <Type Name="SysRoleAndSysPower">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SysRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SysPowerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SysPower_SysRoleAndSysPower" Member="SysPower" ThisKey="SysPowerId" OtherKey="Id" Type="SysPower" IsForeignKey="true" />
      <Association Name="SysRole_SysRoleAndSysPower" Member="SysRole" ThisKey="SysRoleId" OtherKey="Id" Type="SysRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysUser" Member="SysUser">
    <Type Name="SysUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TrueName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdCard" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HeadIcon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WeixinId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EditTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DelTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InsertTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="SysUser_SysUserAndSysRole" Member="SysUserAndSysRole" ThisKey="Id" OtherKey="SysUserId" Type="SysUserAndSysRole" />
    </Type>
  </Table>
  <Table Name="dbo.SysUserAndSysRole" Member="SysUserAndSysRole">
    <Type Name="SysUserAndSysRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SysUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SysRoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SysRole_SysUserAndSysRole" Member="SysRole" ThisKey="SysRoleId" OtherKey="Id" Type="SysRole" IsForeignKey="true" />
      <Association Name="SysUser_SysUserAndSysRole" Member="SysUser" ThisKey="SysUserId" OtherKey="Id" Type="SysUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataCollectDevice" Member="DataCollectDevice">
    <Type Name="DataCollectDevice">
      <Column Name="Id" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PollutionPointId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SIMNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DataTransmitProtocol" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DataReceiveTypeId" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManufacturerContactPeople" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ManufacturerContact" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaintenanceUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaintenanceContactPeople" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaintenanceContact" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Port1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Port2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress3" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Port3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress4" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Port4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
</Database>